name: Publish Develop

on:
  push:
    branches:
      - develop

jobs:
  example-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: DDMMHm
          utcOffset: "+03:00"
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: pankod-k8s
          expirationTime: 1200
      - name: Get nodes
        run: kubectl get nodes
      - name: web docker build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: pankod/refine/refine-example
          tags: sha-${{ steps.current-time.outputs.formattedTime }}
      - name: Deploy refine-example-develop to k8s
        run: |
          cd example
          echo ${{ env.domain }}
          mv ./k8s/refine-example/Chart.yaml ./k8s/refine-example/Chart.old.yaml &&
          cat ./k8s/refine-example/Chart.old.yaml | grep -v appVersion > ./k8s/refine-example/Chart.yaml &&
          echo -e "\r\nappVersion: sha-${{ steps.current-time.outputs.formattedTime }}\r\n" >> ./k8s/refine-example/Chart.yaml &&
          cat ./k8s/refine-example/Chart.yaml
          helm upgrade refine-example-develop ./k8s/refine-example --install --values=./k8s/refine-example/values.yaml \
            --set ingress.enabled=true \
            --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
            --set ingress.annotations."cert-manager\.io/issuer"=letsencrypt-prod \
            --set ingress.hosts[0].host=${{ env.domain }} \
            --set ingress.hosts[0].paths[0]="/" \
            --set ingress.tls[0].secretName=${{ env.domain }} \
            --set ingress.tls[0].hosts[0]=${{ env.domain }} \
        env:
          domain: 'develop.refine.dev'
      - name: Send custom variable to Meercode Build
        uses: meercodeio/meercode-custom-variable@0.1.0
        with:
          meercode-token: ${{ secrets.MEERCODE_TOKEN }}
          url: 'https://develop.refine.dev'