name: Pull Request [closed]

on:
  pull_request:
    types:
      - closed

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR Branch Name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: pr-branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Substring PR Branch Name
        id: substring-pr-branch-name
        run: |
          id=$(echo ${branch:0:7})
          echo "::set-output name=substring::$id"
        env:
          branch: ${{ steps.pr-branch-name.outputs.branch }}
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: pankod-k8s
          expirationTime: 1200
      - name: Get nodes
        run: |
          kubectl get nodes 
      - name: Delete helm release
        run: |
          echo ${{ steps.substring-pr-branch-name.outputs.substring }}
          helm delete ${{ env.branch }}-refine-example || :
          helm delete ${{ env.branch }}-refine-documentation || :
        env:
          branch: ${{ steps.substring-pr-branch-name.outputs.substring }}
 