name: Pull Request [synchronize]

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - "examples/fineFoods/**"
      - "packages/**"

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR Branch Name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: pr-branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Substring PR Branch Name
        id: substring-pr-branch-name
        run: |
          id=$(echo ${branch:0:7})
          echo "::set-output name=substring::$id"
        env:
          branch: ${{ steps.pr-branch-name.outputs.branch }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: pankod-k8s
          expirationTime: 1200
      - name: Get nodes
        run: kubectl get nodes
      - name: backoffice docker build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: pankod/refine/refine-example
          tag_with_sha: true
      - name: Deploy refine-example to k8s
        run: |
          cd examples/fineFoods
          mv ./k8s/refine-example/Chart.yaml ./k8s/refine-example/Chart.old.yaml &&
          cat ./k8s/refine-example/Chart.old.yaml | grep -v appVersion > ./k8s/refine-example/Chart.yaml &&
          echo -e "\r\nappVersion: sha-${GITHUB_SHA::7}\r\n" >> ./k8s/refine-example/Chart.yaml &&
          cat ./k8s/refine-example/Chart.yaml
          helm delete ${{ env.branch }}-refine-example || :
          helm upgrade ${{ env.branch }}-refine-example ./k8s/refine-example --install --atomic --values=./k8s/refine-example/values.yaml \
            --set ingress.enabled=true \
            --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
            --set ingress.annotations."cert-manager\.io/issuer"=letsencrypt-prod \
            --set ingress.hosts[0].host=${{ env.branch }}-${{ env.domain }} \
            --set ingress.hosts[0].paths[0]="/" \
            --set ingress.tls[0].secretName=${{ env.branch }}-${{ env.domain }} \
            --set ingress.tls[0].hosts[0]=${{ env.branch }}-${{ env.domain }} \
        env:
          domain: "refine.pankod.com"
          branch: ${{ steps.substring-pr-branch-name.outputs.substring }}

      - name: Send custom variable to Meercode Build
        uses: meercodeio/meercode-custom-variable@0.1.0
        with:
          meercode-token: ${{ secrets.MEERCODE_TOKEN }}
          url: 'https://${{ steps.substring-pr-branch-name.outputs.substring }}-refine.pankod.com'
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.PANKOD_BOT_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: '[a-z\d-_.\\/]+'
          body-template: |
            Test me! '%basebranch%'
            [Link to %headbranch%](https://${{ steps.substring-pr-branch-name.outputs.substring }}-refine.pankod.com)